(진행)(NYU-56)[Sprint2] NYU-MAIN Restful API 에 맞게 변경
Goorm-IT/NyanYumUnivServer pull request #40
Opened 2022-04-20 01:16 UTC by taeminHan

## **💡 Issue**

[NYU-56]

## **⚡ Content**

- NYU-MAIN build name을 변경 하였습니다.
- NYU-MAIN의 API path를 REST API 규격에 맞춰 변경을 진행하였습니다.
    - UserController 변경
    - StoreController 변경
- DB 개편에 따른 mapper를 변경하였습니다.
    - UserMapper.xml 변경

## **🌟 Point**
- 최대한 RESTful 하게 하려고 했으나 지식이 부족하여 미흡한 부분이 있을 수 있거나 구조적으로 불가능한 부분이 있을 수도 있습니다. 작업 하시면서 중간중간 확인 부탁드립니다.
    - 특히 구조적으로 불가능한 부분은 따로 말씀 부탁드립니다.
- Eureka, SCG는 잠정 보류 하겠습니다.

[NYU-56]: https://nyanyumuniv.atlassian.net/browse/NYU-56

2022-04-20 03:46 UTC, olive-su requested changes
코드가 훨씬 깔끔해지고 직관적이어서 좋은 것 같아요 👏👏
수고하셨습니다~!! 😆

2022-04-20 03:46 UTC, olive-su commented on NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
[Line 61]
(⭐️ 커밋 사항이 아니어서 부득이하게 윗 부분에 코멘트 달았습니다!)

Restful API가 최대한 서술어가 아니라 리소스 위주로 쓰는 게 좋다고 해서 그런데
```java
// @GetMapping("/login")
@GetMapping("/session/new")
```
로 바꾸는 거 어떨까요?
로그아웃도 get방식이길래 뒤에 `/new` path를 추가해봤습니다!

아니면 리소스를 나타내는 거면 다른 명칭도 괜찮을 것 같습니다~

- 관련 레퍼런스 입니다 [Reference](https://stackoverflow.com/questions/7140074/restfully-design-login-or-register-resources)

2022-04-20 03:46 UTC, olive-su commented on NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
>      }
[Line 125]
(⭐️ 커밋 사항이 아니어서 부득이하게 아랫 부분에 코멘트 달았습니다!)

```java
// @GetMapping("/logout")
@GetMapping("/session")
```
위에 Line 60 코멘트 참고 해주세요 !

2022-04-22 00:32 UTC, taeminHan commented on NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
넵 좋네요 그럼 레퍼런스에 맞춰서 다시 변경 하도록 하겠습니다.

2022-04-22 00:53 UTC, taeminHan commented on NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
아니면 아예 Session Controller를 따로 만들까요? 아니면 기존 /user에서 변경할까요?

2022-04-24 13:10 UTC, olive-su commented on NYU-Main/src/main/java/com/nyanyumserver/nyanyumserver/Controller/UserController.java
따로 컨트롤러 안 빼고 path만 바꾸면 될 것 같습니다 ! ㅎㅎ

2022-04-26 00:34 UTC, taeminHan commented
## **💡 Issue**

[NYU-72]

[NYU-56]


## **⚡ Content**

- PR 리뷰를 반영하였습니다.
    - PR 의견 반영 login, logout -> session으로 변경
- MSA, 로드밸런싱을 구현하였으며 서버에 반영하였습니다.
    - NYU-Eureka 프로젝트 추가
    - NYU-GateWay 프로젝트 추가

## **🌟 Point**
- Eureka, SCG 구현 완료 하였으며 서버에 반영하였습니다.
- PR 이후 개발자 테스트 진행 시 IntelliJ에서 Configurations를 변경하여 Eureka, GateWay를 같이 실행해야 동작 합니다. 자세한 내용은 인스펙션 이후에 알려드리겠습니다!

2022-04-26 03:31 UTC, olive-su commented
정말 수고많으셨습니다 ㅠㅠㅠ!
이제는 스웨거가 말썽부리는 일이 없길..🤣

2022-04-26 03:32 UTC, merged